### ISSUE TITLE
Intercept non-event property setting/unsetting

### ISSUE THREAD

**Issue by saviola777** [morko/haxroomie-RoomTrapper#2]
Currently non-event properties are set on the proxied room object without further checks or possibility to intercept. Let's say for example, I want to implement the following behavior:

```
trappedRoom.nonEventProperty = someValue;
```

would result in

```
proxiedRoom.identifier.nonEventProperty = someValue;
```

It would be nice to add something like this to the EventHandler interface, or (as it's not really dealing with events) add a second, optional handler (say, PropertyHandler) for properties. What do you think? I can create a PR if you tell me what kind of solution you have in mind.

**Comment by morko** [comment]
fixed in 43c2b7409f0f502f6fe3dbb376d4d0daabea07d4
